### ISSUE TITLE
beforeEnter params and queryParams

### ISSUE THREAD

**Issue by peebles** [kitze/mobx-router#43] opened 2017-09-03 20:17 UTC
If I type in the browser address bar: http://localhost/home?foo=bar

and I have this route code:

```javascript
    home: new Route({
      path: '/home',
      component: <Home />,
      beforeEnter: (route, params, store, queryParams ) => {
	if ( store.ux.isAuthenticated ) return true;
	console.log( 'route:', route, 'params:', params, 'query:', queryParams );
	store.router.goTo( views.login );
	return false;
      }
```

"params" is an empty JSON object and queryParams seems like it is an observable.  But I cannot seem to get to the query params ( foo=bar ).

What I want to do is to implement "pass-thru" authentication.  The login component needs to "goTo" the original attempted path, in this case "/home?foo=bar".

What am I doing wrong?

**Comment by gordongordon** [comment] 2017-09-11 04:37
This may help!  please change this : `path: '/home/:foo'`! As U know that, in order to get params from url you need to have :/foo . if you want to learn please read over the example from github!

**Comment by peebles** [comment] 2017-09-11 04:42
A few days ago I submitted a pull request.  I believe the beforeEnter() is being called with incorrect parameters.  It is being called with the previous params ... the same ones passed to beforeExit().  beforeEnter() should be getting the params the new route being gone to is going to get.

**Comment by thdk** [comment] 2018-12-08 13:03
I can confirm that beforeEnter is being called with the params of the previous route.

@kitze is that by design?

**Comment by thdk** [comment] 2018-12-12 08:14
@kitze any chance my pull request can be merged to fix and close this issue?

**Closed** 2018-12-12 08:48 UTC
